### ISSUE TITLE
_cachedSampleRates not initialized

### ISSUE THREAD

**Issue by hackwerk** [myriadrf/Novena-RF#21]
I ran into some problems with uhd and osmocom tools and also gqrx on the Novena.

turned out that getSampleRate() was being called without _cachedSampleRates having been initialized, resulting in errors like FATAL: map::at or std::out_of_range errors

I chose to add:

```
_cachedSampleRates[SOAPY_SDR_RX] = 0;
_cachedSampleRates[SOAPY_SDR_TX] = 0;
```

to the constructor, which solved it.

**Comment by guruofquality** [comment]
Cool, thanks
